name: Hello World

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  hello_world:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository's code

    - name: Say Hello
      run: echo "Hello, World!"  # Print 'Hello, World!' to the console
